apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-root
spec:
  capacity:
    storage: 3Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=3
    - proto=tcp
    - hard
    - noatime
  nfs:
    server: 192.168.1.65
    path: /volume1/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-root
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 3Ti
  storageClassName: ""
  volumeName: media-root
