apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-root
spec:
  capacity:
    storage: 2Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  mountOptions: ["nfsvers=4.1","hard","noatime"]
  nfs:
    server: 192.168.1.65
    path: /media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-root
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Ti
  storageClassName: ""
  volumeName: media-root