apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-videos
spec:
  capacity:
    storage: 400Gi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  mountOptions: ["nfsvers=4.1","hard","noatime"]
  nfs:
    server: 192.168.1.65
    path: /media/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-videos
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  storageClassName: ""
  volumeName: jellyfin-videos
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-series
spec:
  capacity:
    storage: 400Gi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  mountOptions: ["nfsvers=4.1","hard","noatime"]
  nfs:
    server: 192.168.1.65
    path: /media/tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-series
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  storageClassName: ""
  volumeName: jellyfin-series
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbitt-download
spec:
  capacity:
    storage: 400Gi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  mountOptions: ["nfsvers=4.1","hard","noatime"]
  nfs:
    server: 192.168.1.65
    path: /media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitt-download
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  storageClassName: ""
  volumeName: qbitt-download